CREATE TABLE IF NOT EXISTS "public"."media" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" "text" NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS "public"."sub_media" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "media_id" bigint NOT NULL REFERENCES "public"."media"("id") ON DELETE CASCADE,
    "name" "text" NOT NULL,
    UNIQUE("media_id", "name")
);

CREATE SEQUENCE IF NOT EXISTS "public"."vendors_id_seq";

CREATE TABLE IF NOT EXISTS "public"."vendors" (
    "id" bigint PRIMARY KEY DEFAULT nextval('public.vendors_id_seq'),
    "type" text,
    "company_name" text,
    "country_dialcode" bigint,
    "contact" text,
    "email" text,
    "alias" text,
    "telephone" text,
    "gstin" text,
    "gstin_date" text,
    "registration" text,
    "pan_number" text,
    "opening_balance" numeric,
    "vendor_bank_name" text,
    "vendor_account_number" text,
    "vendor_confirm_account_number" text,
    "vendor_ifsc_code" text,
    "payment_term_type" text,
    "payment_term_value" bigint,
    "vendor_type" text,
    "date_of_incorporation" text,
    "date_of_birth" text,
    "date_of_marriage_anniversary" text,
    "status" bigint,
    "tds_percentage" text,
    "tds_section" text,
    "ledger_add" text,
    "vendor_document_file_path" text,
    "vendor_document_file_name" text,
    "created_by" text,
    "updated_by" text,
    "activated_by" text,
    "document_deleted_by" text,
    "document_deleted_at" text,
    "activated_at" text,
    "created_at" timestamp with time zone,
    "updated_at" timestamp with time zone,
    "file_url" text,
    "created_at_formatted" text,
    "updated_at_formatted" text,
    "activated_at_formatted" text,
    "document_deleted_at_formatted" text,
    "creator_name" text,
    "updater_name" text,
    "activator_name" text,
    "document_deletor_name" text,
    "media_id" bigint REFERENCES "public"."media"("id"),
    "sub_media_id" bigint REFERENCES "public"."sub_media"("id"),
    "contact_person" text,
    "country_code" text DEFAULT 'IN',
    "payment_term_invoice_date" date
);

CREATE TABLE IF NOT EXISTS "public"."vendor_addresses" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "vendor_id" bigint NOT NULL REFERENCES "public"."vendors"("id") ON DELETE CASCADE,
    "address" text NOT NULL,
    "country" text DEFAULT 'India',
    "country_code" text DEFAULT 'IN',
    "state" text NOT NULL,
    "city" text,
    "zipcode" text,
    "is_default" boolean DEFAULT false,
    "created_at" timestamp with time zone DEFAULT now(),
    "updated_at" timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "public"."clients" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "type" text,
    "company_name" text,
    "country_dialcode" bigint,
    "contact" numeric,
    "email" text,
    "alias" text,
    "gstin" text,
    "gstin_date" date,
    "registration" text,
    "pan_number" text,
    "status" bigint,
    "tds_percentage" text,
    "tds_section" text,
    "contact_person" text
);
